// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRKZK1Wh5UKAOaNZiMEtgiT2lj0BSn84c',
    appId: '1:878885504222:web:d0bdf8b4f87ce49d5e2e4f',
    messagingSenderId: '878885504222',
    projectId: 'ecommerce-mobile-a7d98',
    authDomain: 'ecommerce-mobile-a7d98.firebaseapp.com',
    storageBucket: 'ecommerce-mobile-a7d98.firebasestorage.app',
    measurementId: 'G-LPVD3G906G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1w1-JE3R3pInjVcwtK0PY2JtNPx3c8pE',
    appId: '1:878885504222:android:db9f59a51a7b196d5e2e4f',
    messagingSenderId: '878885504222',
    projectId: 'ecommerce-mobile-a7d98',
    storageBucket: 'ecommerce-mobile-a7d98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxZ4YCHC1zLiBhRH6qSTDjsEOUqsY0LPg',
    appId: '1:878885504222:ios:0f0ffaeef65a3a475e2e4f',
    messagingSenderId: '878885504222',
    projectId: 'ecommerce-mobile-a7d98',
    storageBucket: 'ecommerce-mobile-a7d98.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxZ4YCHC1zLiBhRH6qSTDjsEOUqsY0LPg',
    appId: '1:878885504222:ios:0f0ffaeef65a3a475e2e4f',
    messagingSenderId: '878885504222',
    projectId: 'ecommerce-mobile-a7d98',
    storageBucket: 'ecommerce-mobile-a7d98.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRKZK1Wh5UKAOaNZiMEtgiT2lj0BSn84c',
    appId: '1:878885504222:web:9347835a60bf90c85e2e4f',
    messagingSenderId: '878885504222',
    projectId: 'ecommerce-mobile-a7d98',
    authDomain: 'ecommerce-mobile-a7d98.firebaseapp.com',
    storageBucket: 'ecommerce-mobile-a7d98.firebasestorage.app',
    measurementId: 'G-LQ00GK8KLS',
  );
}
